// Deterministic illustrative cadastral fabric around a real dataset parcel.
// The dataset parcel keeps its true polygon; neighbouring plots are generated by recursive
// convex splitting of an irregular village outline (seeded by ULPIN, so identical every load).

function rng(seedStr) {
  let h = 1779033703 ^ seedStr.length;
  for (let i = 0; i < seedStr.length; i++) { h = Math.imul(h ^ seedStr.charCodeAt(i), 3432918353); h = (h << 13) | (h >>> 19); }
  return () => { h = Math.imul(h ^ (h >>> 16), 2246822507); h = Math.imul(h ^ (h >>> 13), 3266489909); h ^= h >>> 16; return (h >>> 0) / 4294967296; };
}

const area = (p) => { let a = 0; for (let i = 0; i < p.length; i++) { const [x1, y1] = p[i], [x2, y2] = p[(i + 1) % p.length]; a += x1 * y2 - x2 * y1; } return Math.abs(a) / 2; };
const centroid = (p) => { let x = 0, y = 0; p.forEach(q => { x += q[0]; y += q[1]; }); return [x / p.length, y / p.length]; };

// Keep the part of convex polygon p where nx*x + ny*y <= c (Sutherland–Hodgman, one half-plane).
function clip(p, nx, ny, c) {
  const out = [];
  for (let i = 0; i < p.length; i++) {
    const a = p[i], b = p[(i + 1) % p.length];
    const da = nx * a[0] + ny * a[1] - c, db = nx * b[0] + ny * b[1] - c;
    if (da <= 0) out.push(a);
    if ((da < 0) !== (db < 0) && da !== db) { const t = da / (da - db); out.push([a[0] + t * (b[0] - a[0]), a[1] + t * (b[1] - a[1])]); }
  }
  return out;
}

function hull(pts) {
  pts = pts.slice().sort((a, b) => a[0] - b[0] || a[1] - b[1]);
  const cross = (o, a, b) => (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0]);
  const lo = [], up = [];
  for (const p of pts) { while (lo.length >= 2 && cross(lo[lo.length - 2], lo[lo.length - 1], p) <= 0) lo.pop(); lo.push(p); }
  for (const p of pts.reverse()) { while (up.length >= 2 && cross(up[up.length - 2], up[up.length - 1], p) <= 0) up.pop(); up.push(p); }
  return lo.slice(0, -1).concat(up.slice(0, -1));
}

// Split along the cell's longer side (in the village's rotated frame) -> field strips.
function subdivide(cell, target, rand, phi, out, depth = 0) {
  const a = area(cell);
  if (a < target * (0.55 + rand() * 0.9) || depth > 14) { out.push(cell); return; }
  const ux = Math.cos(phi), uy = Math.sin(phi);
  let min1 = Infinity, max1 = -Infinity, min2 = Infinity, max2 = -Infinity;
  cell.forEach(([x, y]) => { const s = x * ux + y * uy, r = -x * uy + y * ux; min1 = Math.min(min1, s); max1 = Math.max(max1, s); min2 = Math.min(min2, r); max2 = Math.max(max2, r); });
  const alongU = (max1 - min1) >= (max2 - min2) * (0.7 + rand() * 0.5);
  const wobble = (rand() - 0.5) * 0.28;
  const ang = phi + (alongU ? 0 : Math.PI / 2) + wobble;
  const nx = Math.cos(ang), ny = Math.sin(ang);
  let lo = Infinity, hi = -Infinity;
  cell.forEach(([x, y]) => { const d = nx * x + ny * y; lo = Math.min(lo, d); hi = Math.max(hi, d); });
  const c = lo + (hi - lo) * (0.3 + rand() * 0.4);
  const A = clip(cell, nx, ny, c), B = clip(cell, -nx, -ny, -c);
  if (A.length < 3 || B.length < 3 || area(A) < 30 || area(B) < 30) { out.push(cell); return; }
  subdivide(A, target, rand, phi, out, depth + 1);
  subdivide(B, target, rand, phi, out, depth + 1);
}

const cache = new Map();

/** Returns { plots: [{ id, label, latlngs }], remainder: latlngs } for the village around `parcel`. */
export function villageFabric(parcel, neighbours = []) {
  if (cache.has(parcel.ulpin)) return cache.get(parcel.ulpin);
  const rand = rng(parcel.ulpin);
  const lat0 = parcel.centroid.lat, lon0 = parcel.centroid.lon;
  const kx = Math.cos(lat0 * Math.PI / 180) * 111320, ky = 110540;
  const toXY = ([lon, lat]) => [(lon - lon0) * kx, (lat - lat0) * ky];
  const toLL = ([x, y]) => [lat0 + y / ky, lon0 + x / kx];

  const urban = parcel.context === "urban";
  const recordHa = parcel.area.record || 1;
  const R = urban ? 260 : 620 + rand() * 180;
  const target = Math.max(urban ? 350 : 4000, recordHa * 10000 * (urban ? 0.6 : 0.8));
  const phi = (rand() - 0.5) * 0.9;

  const outline = [];
  for (let i = 0; i < 14; i++) {
    const a = (i / 14) * Math.PI * 2 + (rand() - 0.5) * 0.3;
    const r = R * (0.72 + rand() * 0.42);
    outline.push([Math.cos(a) * r * 1.2, Math.sin(a) * r]);
  }
  let village = hull(outline);
  // Voronoi cut: nearby villages meet along the bisector instead of overlapping.
  for (const n of neighbours) {
    const [nx, ny] = toXY([n.lon, n.lat]);
    const d = Math.hypot(nx, ny);
    if (d < 1 || d > 4000) continue;
    const ux = nx / d, uy = ny / d;
    village = clip(village, ux, uy, d / 2 - 12);
  }

  // Carve the parcel's bounding box out as its own cell so the fabric wraps around it.
  const pxy = parcel.geometry.slice(0, -1).map(toXY);
  const xs = pxy.map(p => p[0]), ys = pxy.map(p => p[1]);
  const pad = urban ? 2 : 5;
  const x0 = Math.min(...xs) - pad, x1 = Math.max(...xs) + pad, y0 = Math.min(...ys) - pad, y1 = Math.max(...ys) + pad;
  const left = clip(village, 1, 0, x0), right = clip(village, -1, 0, -x1);
  const mid = clip(clip(village, -1, 0, -x0), 1, 0, x1);
  const bottom = clip(mid, 0, 1, y0), top = clip(mid, 0, -1, -y1);
  const center = clip(clip(mid, 0, -1, -y0), 0, 1, y1);

  const cells = [];
  [left, right, bottom, top].forEach(c => { if (c.length >= 3) subdivide(c, target, rand, phi, cells); });

  // Survey numbers near the parcel's own number, nearer plots get nearer numbers.
  const base = parseInt(parcel.nativeId.value, 10) || 100;
  const used = new Set([base]);
  const withDist = cells.map(c => { const [x, y] = centroid(c); return { c, d: Math.hypot(x, y) }; }).sort((a, b) => a.d - b.d);
  const plots = withDist.map(({ c }, i) => {
    let n; let guard = 0;
    do { n = Math.max(1, base + Math.round((rand() - 0.45) * (12 + i * 2.2))); } while (used.has(n) && guard++ < 50);
    used.add(n);
    const part = rand() < 0.28 ? `/${1 + Math.floor(rand() * 3)}` : "";
    return { id: `${parcel.ulpin}-n${i}`, label: `${n}${part}`, latlngs: c.map(toLL), center: toLL(centroid(c)) };
  });
  const result = { plots, remainder: center.length >= 3 ? center.map(toLL) : null, outline: village.map(toLL) };
  cache.set(parcel.ulpin, result);
  return result;
}
